"""empty message

Revision ID: 5a4c8460cb25
Revises: afa854d6eec3
Create Date: 2023-02-20 13:44:37.510896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a4c8460cb25'
down_revision = 'afa854d6eec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=postgresql.BYTEA(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=postgresql.BYTEA(),
               nullable=False)

    # ### end Alembic commands ###
